### PR TITLE
French translation : new proposal

### PR DESCRIPTION
**Pull request by bergerc**
Following the request to review the French translation, here is a proposition for more accurate translation.
I also add a comment in the mantis tool unders the bug https://bugs.cacert.org/view.php?id=970

### CODE REVIEW

**Comment by Ted-CAcert** [comment]
Hi,

do you have an idea why every line in lang/french.php is shown as modified in the diff? It makes it very hard to spot the real differences...
Is it possible that you changed the line ending convention from DOS (CR/LF) to unix (CR only) or vice versa?

N.B.: I'm still learning how to use Git and GitHub efficiently, so you should take into account that I might just be too dumb to see the reason. :-)

**Comment by bergerc** [comment]
Hi, sorry for that, yes i'm working under an UNIX system, I create a new pull request immediately.

I'm also new to git/github, hope you will be able to diff between this new version and the initial one... I didn't manage to do that.

**Comment by Ted-CAcert** [comment]
Now it's much better to compare!

I can look at the diff by clicking the "Files" tab of the Pull Request. lang/french.php is the last one of the files. I guess the other files are shown because I merged some other branches into release before you forked your copy, but after branch bug-970 was created.

I'll try to merge release into bug-970 and hope that the other files will not be shown anymore...

**Comment by eruedin** [comment]
Here, the Version 1 from bugtracker has been corrected, although in the bugtracker already existed a newer version (french2.php). I have merged the version here with the version 2 from the bugtracker. I stored this united version in the bug tracker as a document named french3.php

https://bugs.cacert.org/view.php?id=970

**Pull request closed without merging**
